apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vcluster-custom-test-argocd-cluster
  namespace: argocd
  labels:
    app: vcluster
    instance: custom-test
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: vcluster-custom-test
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          cluster_name: custom-test
          cluster_role: worker
          environment: development
          enable_argocd: "true"
          enable_cert_manager: "true"
          enable_external_secrets: "true"
          enable_ingress_nginx: "true"
          enable_metrics_server: "true"
        annotations:
          addons_repo_url: https://github.com/jamesatintegratnio/gitops_homelab_2_0
          addons_repo_revision: main
          addons_repo_basepath: addons/
          addons_repo_path: charts/application-sets
          managed-by: argocd.argoproj.io
          cert_manager_namespace: cert-manager
          external_dns_namespace: external-dns
          nfs_subdir_external_provisioner_namespace: nfs-provisioner
          cluster_name: custom-test
          environment: development
          reconcile-token: "20260119195500"
      type: Opaque
  data:
    - secretKey: name
      remoteRef:
        key: vcluster-custom-test-kubeconfig
        property: argocd-name
    - secretKey: server
      remoteRef:
        key: vcluster-custom-test-kubeconfig
        property: argocd-server
    - secretKey: config
      remoteRef:
        key: vcluster-custom-test-kubeconfig
        property: argocd-config
