apiVersion: v1
kind: Namespace
metadata:
  name: vcluster-media
  labels:
    app: vcluster
    instance: media
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
