apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vcluster-media-kubeconfig
  namespace: vcluster-media
  labels:
    app: vcluster
    instance: media
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: vcluster-media-kubeconfig-external
    creationPolicy: Owner
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: vcluster-media-kubeconfig
        property: kubeconfig
