apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vcluster-media-argocd-cluster
  namespace: argocd
  labels:
    app: vcluster
    instance: media
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: vcluster-media
    creationPolicy: Owner
    template:
      metadata:
        labels:
            argocd.argoproj.io/secret-type: cluster
            cluster_name: media
            cluster_role: worker
            cluster_type: vcluster
            enable_argocd: "true"
            enable_cert_manager: "true"
            enable_external_secrets: "true"
            enable_gateway_api_crds: "true"
            enable_nginx_gateway_fabric: "true"
            environment: production
        annotations:
            addons_repo_basepath: addons/
            addons_repo_path: charts/application-sets
            addons_repo_revision: main
            addons_repo_url: https://github.com/jamesatintegratnio/gitops_homelab_2_0
            cert_manager_namespace: cert-manager
            cluster_name: media
            environment: production
            external_dns_namespace: external-dns
            managed-by: argocd.argoproj.io
            nfs_subdir_external_provisioner_namespace: nfs-provisioner
      type: Opaque
  data:
    - secretKey: name
      remoteRef:
        key: vcluster-media-kubeconfig
        property: argocd-name
    - secretKey: server
      remoteRef:
        key: vcluster-media-kubeconfig
        property: argocd-server
    - secretKey: config
      remoteRef:
        key: vcluster-media-kubeconfig
        property: argocd-config
