apiVersion: platform.integratn.tech/v1alpha1
kind: ArgoCDProject
metadata:
  name: vcluster-test-3
  namespace: platform-requests
spec:
  name: vcluster-test-3
  namespace: argocd
  description: VCluster project for test3
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/managed-by: kratix
    kratix.io/promise-name: vcluster-orchestrator
    kratix.io/resource-request: test3
    argocd.argoproj.io/project-group: appteam
  sourceRepos:
    - https://charts.loft.sh
  destinations:
    - server: https://kubernetes.default.svc
      namespace: vcluster-test-3
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
