apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    addons_repo_basepath: addons/
    addons_repo_path: charts/application-sets
    addons_repo_revision: main
    addons_repo_url: https://github.com/jamesatintegratnio/gitops_homelab_2_0.git
    cert_manager_namespace: cert-manager
    cluster_name: demo
    environment: production
    external_dns_namespace: external-dns
    managed-by: argocd.argoproj.io
    nfs_subdir_external_provisioner_namespace: nfs-provisioner
    platform.integratn.tech/base-domain: integratn.tech
    platform.integratn.tech/base-domain-sanitized: integratn-tech
    workload_repo_basepath: ""
    workload_repo_path: workloads
    workload_repo_revision: main
    workload_repo_url: https://github.com/jamesatintegratnio/gitops_homelab_2_0
  labels:
    akuity.io/argo-cd-cluster-name: demo
    app.kubernetes.io/component: argocd-cluster
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: external-secret
    argocd.argoproj.io/secret-type: cluster
    cluster_name: demo
    cluster_role: vcluster
    cluster_type: vcluster
    enable_argocd: "true"
    enable_cert_manager: "true"
    enable_external_dns: "true"
    enable_external_secrets: "true"
    enable_gateway_api_crds: "true"
    enable_nginx_gateway_fabric: "true"
    environment: production
    kratix.io/promise-name: argocd-cluster-registration
    kratix.io/resource-name: demo
  name: demo-argocd-cluster
  namespace: argocd
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: demo-kubeconfig
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: cluster-demo
    template:
      data:
        config: '{{ index . "argocd-config" }}'
        name: '{{ index . "argocd-name" }}'
        server: '{{ index . "argocd-server" }}'
      engineVersion: v2
      metadata:
        annotations:
          addons_repo_basepath: addons/
          addons_repo_path: charts/application-sets
          addons_repo_revision: main
          addons_repo_url: https://github.com/jamesatintegratnio/gitops_homelab_2_0.git
          cert_manager_namespace: cert-manager
          cluster_name: demo
          environment: production
          external_dns_namespace: external-dns
          managed-by: argocd.argoproj.io
          nfs_subdir_external_provisioner_namespace: nfs-provisioner
          platform.integratn.tech/base-domain: integratn.tech
          platform.integratn.tech/base-domain-sanitized: integratn-tech
          workload_repo_basepath: ""
          workload_repo_path: workloads
          workload_repo_revision: main
          workload_repo_url: https://github.com/jamesatintegratnio/gitops_homelab_2_0
        labels:
          akuity.io/argo-cd-cluster-name: demo
          argocd.argoproj.io/secret-type: cluster
          cluster_name: demo
          cluster_role: vcluster
          cluster_type: vcluster
          enable_argocd: "true"
          enable_cert_manager: "true"
          enable_external_dns: "true"
          enable_external_secrets: "true"
          enable_gateway_api_crds: "true"
          enable_nginx_gateway_fabric: "true"
          environment: production
          integratn.tech/cluster-name: demo
          integratn.tech/environment: production
      type: Opaque
