apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: etcd-ca
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: demo
  name: demo-etcd-ca
  namespace: demo
spec:
  commonName: demo-etcd-ca
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: demo-etcd-selfsigned
  privateKey:
    algorithm: RSA
    size: 2048
  secretName: demo-etcd-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: etcd-issuer
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: demo
  name: demo-etcd-selfsigned
  namespace: demo
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: etcd-ca-issuer
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: demo
  name: demo-etcd-ca
  namespace: demo
spec:
  ca:
    secretName: demo-etcd-ca
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: etcd-certs-job
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: demo
  name: demo-etcd-certs-merge
  namespace: demo
spec:
  template:
    metadata:
      labels:
        app: etcd-certs-merge
      name: ""
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |-
          set -e
          echo "Waiting for certificates to be ready..."

          # Wait for CA cert
          until kubectl get secret demo-etcd-ca -n demo 2>/dev/null; do
            echo "Waiting for CA certificate..."
            sleep 2
          done

          # Wait for server cert
          until kubectl get secret demo-etcd-server -n demo 2>/dev/null; do
            echo "Waiting for server certificate..."
            sleep 2
          done

          # Wait for peer cert
          until kubectl get secret demo-etcd-peer -n demo 2>/dev/null; do
            echo "Waiting for peer certificate..."
            sleep 2
          done

          echo "All certificates ready, merging..."

          # Extract certs
          CA_CRT=$(kubectl get secret demo-etcd-ca -n demo -o jsonpath='{.data.tls\.crt}')
          SERVER_CRT=$(kubectl get secret demo-etcd-server -n demo -o jsonpath='{.data.tls\.crt}')
          SERVER_KEY=$(kubectl get secret demo-etcd-server -n demo -o jsonpath='{.data.tls\.key}')
          PEER_CRT=$(kubectl get secret demo-etcd-peer -n demo -o jsonpath='{.data.tls\.crt}')
          PEER_KEY=$(kubectl get secret demo-etcd-peer -n demo -o jsonpath='{.data.tls\.key}')

          # Create merged secret
          kubectl create secret generic demo-etcd-certs -n demo \
            --from-literal=etcd-ca.crt="$(echo $CA_CRT | base64 -d)" \
            --from-literal=etcd-server.crt="$(echo $SERVER_CRT | base64 -d)" \
            --from-literal=etcd-server.key="$(echo $SERVER_KEY | base64 -d)" \
            --from-literal=etcd-peer.crt="$(echo $PEER_CRT | base64 -d)" \
            --from-literal=etcd-peer.key="$(echo $PEER_KEY | base64 -d)" \
            --dry-run=client -o yaml | kubectl apply -f -

          echo "Certificate merge complete!"
        image: bitnami/kubectl:latest
        name: merge-certs
      restartPolicy: OnFailure
      serviceAccountName: vc-demo
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: etcd-server-cert
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: demo
  name: demo-etcd-server
  namespace: demo
spec:
  commonName: demo-etcd
  dnsNames:
  - demo-etcd
  - demo-etcd.demo
  - demo-etcd.demo.svc
  - demo-etcd.demo.svc.cluster.local
  - demo-etcd-headless
  - demo-etcd-headless.demo
  - demo-etcd-headless.demo.svc
  - demo-etcd-headless.demo.svc.cluster.local
  - demo-etcd-0
  - demo-etcd-0.demo-etcd-headless.demo
  - demo-etcd-0.demo-etcd-headless.demo.svc
  - demo-etcd-0.demo-etcd-headless.demo.svc.cluster.local
  - demo-etcd-1
  - demo-etcd-1.demo-etcd-headless.demo
  - demo-etcd-1.demo-etcd-headless.demo.svc
  - demo-etcd-1.demo-etcd-headless.demo.svc.cluster.local
  - demo-etcd-2
  - demo-etcd-2.demo-etcd-headless.demo
  - demo-etcd-2.demo-etcd-headless.demo.svc
  - demo-etcd-2.demo-etcd-headless.demo.svc.cluster.local
  - localhost
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: demo-etcd-ca
  privateKey:
    algorithm: RSA
    size: 2048
  secretName: demo-etcd-server
  secretTemplate:
    labels:
      app.kubernetes.io/instance: demo
      app.kubernetes.io/name: etcd-server-cert
  usages:
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: demo
    app.kubernetes.io/managed-by: kratix
    app.kubernetes.io/name: etcd-peer-cert
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: demo
  name: demo-etcd-peer
  namespace: demo
spec:
  commonName: demo-etcd
  dnsNames:
  - demo-etcd
  - demo-etcd.demo
  - demo-etcd.demo.svc
  - demo-etcd.demo.svc.cluster.local
  - demo-etcd-headless
  - demo-etcd-headless.demo
  - demo-etcd-headless.demo.svc
  - demo-etcd-headless.demo.svc.cluster.local
  - demo-etcd-0
  - demo-etcd-0.demo-etcd-headless.demo
  - demo-etcd-0.demo-etcd-headless.demo.svc
  - demo-etcd-0.demo-etcd-headless.demo.svc.cluster.local
  - demo-etcd-1
  - demo-etcd-1.demo-etcd-headless.demo
  - demo-etcd-1.demo-etcd-headless.demo.svc
  - demo-etcd-1.demo-etcd-headless.demo.svc.cluster.local
  - demo-etcd-2
  - demo-etcd-2.demo-etcd-headless.demo
  - demo-etcd-2.demo-etcd-headless.demo.svc
  - demo-etcd-2.demo-etcd-headless.demo.svc.cluster.local
  - localhost
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: demo-etcd-ca
  privateKey:
    algorithm: RSA
    size: 2048
  secretName: demo-etcd-peer
  secretTemplate:
    labels:
      app.kubernetes.io/instance: demo
      app.kubernetes.io/name: etcd-peer-cert
  usages:
  - server auth
  - client auth
