apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: media-argocd-cluster
  namespace: vcluster-media
  labels:
    app.kubernetes.io/name: external-secret
    app.kubernetes.io/component: argocd-cluster
    app.kubernetes.io/managed-by: kratix
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: media
    argocd.argoproj.io/secret-type: cluster
    akuity.io/argo-cd-cluster-name: "media"
    argocd.argoproj.io/secret-type: "cluster"
    cluster_name: "media"
    cluster_role: "vcluster"
    cluster_type: "vcluster"
    enable_argocd: "true"
    enable_cert_manager: "true"
    enable_external_dns: "true"
    enable_external_secrets: "true"
    enable_gateway_api_crds: "true"
    enable_nginx_gateway_fabric: "true"
    environment: "production"
  annotations:
    addons_repo_basepath: "addons/"
    addons_repo_path: "charts/application-sets"
    addons_repo_revision: "main"
    addons_repo_url: "https://github.com/jamesatintegratnio/gitops_homelab_2_0"
    cert_manager_namespace: "cert-manager"
    cluster_name: "media"
    environment: "production"
    external_dns_namespace: "external-dns"
    managed-by: "argocd.argoproj.io"
    nfs_subdir_external_provisioner_namespace: "nfs-provisioner"
    platform.integratn.tech/base-domain: "integratn.tech"
    platform.integratn.tech/base-domain-sanitized: "integratn-tech"
    platform.integratn.tech/reconcile-at: "2026-02-08T04:32:49Z"
    workload_repo_basepath: ""
    workload_repo_path: "workloads"
    workload_repo_revision: "main"
    workload_repo_url: "https://github.com/jamesatintegratnio/gitops_homelab_2_0"
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: cluster-media-integratn-tech
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          integratn.tech/vcluster-name: "media"
          integratn.tech/environment: "production"
          akuity.io/argo-cd-cluster-name: "media"
          argocd.argoproj.io/secret-type: "cluster"
          cluster_name: "media"
          cluster_role: "vcluster"
          cluster_type: "vcluster"
          enable_argocd: "true"
          enable_cert_manager: "true"
          enable_external_dns: "true"
          enable_external_secrets: "true"
          enable_gateway_api_crds: "true"
          enable_nginx_gateway_fabric: "true"
          environment: "production"
        annotations:
          addons_repo_basepath: "addons/"
          addons_repo_path: "charts/application-sets"
          addons_repo_revision: "main"
          addons_repo_url: "https://github.com/jamesatintegratnio/gitops_homelab_2_0"
          cert_manager_namespace: "cert-manager"
          cluster_name: "media"
          environment: "production"
          external_dns_namespace: "external-dns"
          managed-by: "argocd.argoproj.io"
          nfs_subdir_external_provisioner_namespace: "nfs-provisioner"
          platform.integratn.tech/base-domain: "integratn.tech"
          platform.integratn.tech/base-domain-sanitized: "integratn-tech"
          platform.integratn.tech/reconcile-at: "2026-02-08T04:32:49Z"
          workload_repo_basepath: ""
          workload_repo_path: "workloads"
          workload_repo_revision: "main"
          workload_repo_url: "https://github.com/jamesatintegratnio/gitops_homelab_2_0"
      data:
        name: |
          {{ .argocd_name }}
        server: |
          {{ .argocd_server }}
        config: |
          {{ .argocd_config }}
  dataFrom:
    - extract:
        key: vcluster-media-kubeconfig
        conversionStrategy: Default
        decodingStrategy: None
  refreshInterval: 15m
