apiVersion: v1
kind: Namespace
metadata:
  name: vcluster-media
  labels:
    app.kubernetes.io/name: vcluster-namespace
    app.kubernetes.io/managed-by: kratix
    kratix.io/promise-name: vcluster-orchestrator-v2
    kratix.io/resource-name: media
    vcluster.loft.sh/namespace: "true"
