apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vcluster-test
  namespace: argocd
  annotations:
    {}
  labels:
    app.kubernetes.io/managed-by: kratix
    kratix.io/promise-name: argocd-project
    kratix.io/resource-name: vcluster-test

spec:
  description: Project for vcluster test
  sourceRepos:
    - https://github.com/jamesatintegratnio/gitops_homelab_2_0
    - https://charts.loft.sh
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
