apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterCoredns
metadata:
  name: test2
  namespace: platform-requests
spec:
  name: test2
  targetNamespace: vcluster-test-2
  clusterDomain: cluster.local
