apiVersion: platform.integratn.tech/v1alpha1
kind: VClusterCore
metadata:
  name: media
  namespace: platform-requests
spec:
  name: media
  targetNamespace: vcluster-media
  valuesYaml: |
    controlPlane:
      distro:
        k8s:
          enabled: true
          version: "v1.34.3"
      statefulSet:
        highAvailability:
          replicas: 3
        image:
          repository: "loft-sh/vcluster-oss"
        persistence:
          volumeClaim:
            enabled: true
            size: "10Gi"
        resources:
          requests:
            cpu: "200m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
      coredns:
        enabled: true
        deployment:
          replicas: 2
        overwriteConfig: |
          .:1053 {
            errors
            health
            ready
            kubernetes cluster.local in-addr.arpa ip6.arpa {
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
            }
            prometheus 0.0.0.0:9153
            forward . /etc/resolv.conf
            cache 30
            loop
            reload
            loadbalance
          }
      proxy:
        extraSANs:
          - "media.integratn.tech"
      service:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "media.integratn.tech"
        spec:
          type: LoadBalancer
          ports:
            - name: https
              port: 443
              protocol: TCP
              targetPort: 8443
            - name: https-alt
              port: 8443
              protocol: TCP
              targetPort: 8443
      backingStore:
        etcd:
          deploy:
            enabled: true
            statefulSet:
              highAvailability:
                replicas: 3
    deploy:
      metallb:
        enabled: true
    integrations:
      externalSecrets:
        enabled: true
        webhook:
          enabled: true
        sync:
          fromHost:
            clusterStores:
              enabled: true
              selector:
                matchLabels:
                  integratn.tech/cluster-secret-store: onepassword-store
      metricsServer:
        enabled: true
      certManager:
        enabled: true
        sync:
          fromHost:
            clusterIssuers:
              enabled: true
              selector:
                labels:
                  integratn.tech/cluster-issuer: letsencrypt-prod
    telemetry:
      enabled: false
    networking:
      advanced:
        clusterDomain: "cluster.local"
    sync:
      toHost:
        pods:
          enabled: true
      fromHost:
        storageClasses:
          enabled: true
        secrets:
          enabled: true
          mappings:
            byName:
              "external-secrets/eso-onepassword-token": "external-secrets/eso-onepassword-token"
    rbac:
      clusterRole:
        enabled: true
        extraRules:
          - apiGroups: [""]
            resources: ["secrets"]
            verbs: ["get", "list", "watch"]
            resourceNames:
              - "eso-onepassword-token"
    exportKubeConfig:
      server: "https://media.integratn.tech:443"
